pixel_scale = 3
sprites_per_scanline = 8

[ctrl1_layout]
left = "A"
up = "W"
down = "S"
right = "D"
a = "F"
b = "G"
start = "T"
select = "Y"

[ctrl2_layout]
left = "Left"
up = "Up"
down = "Down"
right = "Right"
a = "RShift"
b = "Enter"
start = "B"
select = "B"

[emu_controls]
save_state = "Q"
load_state = "E"
pause = "P"
reset = "R"

[overscan]
top = 8
bottom = 8
left = 0
right = 0
